[package]
name = "governance-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
toml = "0.7"
alloy = { version = "0.8", features = ["full"] }
chrono = "0.4"
anyhow = { version = "1.0", default-features = false }
